name: Flutter Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'

    - name: Auto Generate Missing Project Files
      run: |
        # হারিয়ে যাওয়া সব ফাইল ও ফোল্ডার অটোমেটিক তৈরি করার স্ক্রিপ্ট
        mkdir -p temp_lib
        if [ -f main.dart ]; then
          mv main.dart temp_lib/main.dart
        fi
        flutter create --org com.example --project-name jewellery_app . --overwrite
        rm -rf lib
        mv temp_lib lib
        
    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: jewelry-shop-app
        path: build/app/outputs/flutter-apk/app-release.apk
